#!/bin/bash
git_branch_local=$(echo $GIT_BRANCH | sed -e "s|origin/||g")

ssh -i '~/node-app.pem' ubuntu@52.221.196.71 <<EOF
 cd ~/node_js_ci-cd/
 git checkout ${git_branch_local}
 git pull
 pm2 delete all
 pm2 start ecosystem.config.js
 pm2 restart server_${git_branch_local}
EOF
