#!/bin/sh
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

ssh -i '~/node-app.pem' ubuntu@13.250.37.223 <<EOF
 cd ~/node_js_ci-cd/
 git checkout ${branch}
 git pull
 pm2 delete all
 pm2 start ecosystem.config.js
 pm2 restart server_${branch}
EOF
